- name: Install Bacula Director & Storage
  hosts: directors
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - bacula-director-mysql
          - bacula-sd
          - bacula-console
        update_cache: yes
        state: present

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - bacula-director
        - bacula-sd
