- name: Install Bacula File Daemon
  hosts: clients
  become: yes
  tasks:
    - name: Install bacula-fd
      apt:
        name: bacula-fd
        update_cache: yes
        state: present

    - name: Enable bacula-fd
      systemd:
        name: bacula-fd
        enabled: yes
        state: started
